package com.ras.baymax.entities.enums;

public enum Specialty {
    SURGEON, NEUROLOGIST; ORTHOPEDICIST, CARDIOLOGIST, OPHTHALMOLOGIST, PNEUMOLOGIST, DERMATOLOGIST, PEDIATRICIAN, ENDOCRINOLOGIST, HEMATOLOGIST;
}
