# Generated by Django 5.0.3 on 2024-04-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workingTime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('work_hours', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workingTime.workingtime')),
            ],
        ),
    ]
