# Generated by Django 5.0.3 on 2024-03-30 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baymax', '0002_doctor_nurse_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('birth', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('birth', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_start', models.TimeField()),
                ('work_finish', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='crm',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baymax.doctor')),
                ('nurse_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baymax.nurse')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_hours',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='baymax.workingtime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='work_hours',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='baymax.workingtime'),
            preserve_default=False,
        ),
    ]
