# Generated by Django 5.0.3 on 2024-04-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baymax', '0006_rename_systemuser_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
