# Generated by Django 5.0.3 on 2024-04-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baymax', '0007_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apointment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='apointment',
            name='nurse_id',
        ),
        migrations.DeleteModel(
            name='Companion',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='work_hours',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='work_hours',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Apointment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='WorkingTime',
        ),
    ]
