# Generated by Django 5.0.3 on 2024-04-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baymax', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='professional_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
