# Generated by Django 5.0.3 on 2024-04-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baymax', '0011_alter_user_professional_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
