# Generated by Django 5.0.3 on 2024-04-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_start', models.TimeField()),
                ('work_finish', models.TimeField()),
            ],
        ),
    ]
