# Generated by Django 5.0.3 on 2024-04-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('birth', models.CharField(max_length=10)),
            ],
        ),
    ]
